version: 0.2

phases:
  install:
    commands:
      - yum -y update
      - yum -y install unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
  build:
    commands:
      - cd path/to/your/terraform/code
      - terraform apply -auto-approve
