version: 0.2

phases:
  install:
  pre_build:
    commands:
      - apt-get update
      - apt-get -y install unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform_1.0.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - cd path/to/your/terraform/code
      - terraform init
      - terraform apply -auto-approve
